### PR TITLE
Remove empty scripts

### PR DESCRIPTION
**Pull request by farribeiro**
@FabioBeneditto consider unecessary that conflicts

```
# Conflicts:
#	wine-jogos/DirtShowdown.sh
#	wine-jogos/LEGO.Worlds.sh
#	wine-jogos/TrickyTowers.sh
#	wine-jogos/Worm_WMD.sh
#	wine-jogos/black_squad.sh
#	wine-jogos/ffactory.sh
#	wine-jogos/giana.sh
```

### CODE REVIEW

**Comment by FabioBeneditto** [comment]
I agree. Burn them all.

**Comment by farribeiro** [comment]
But isn't the topic of your PR, @FabioBeneditto

**Comment by FabioBeneditto** [comment]
My PR was merged, I can't revert it.

**Comment by farribeiro** [comment]
Ok! Conflicts resolved!

Now merge waits

**Comment by nwildner** [comment]
Done

**Pull request merged**
